// Tiny deterministic codec fixtures, generated locally with ImageMagick.
const imageFixtures = <String, String>{
  'jpg': '/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAMCAgICAgMCAgIDAwMDBAYEBAQEBAgGBgUGCQgKCgkICQkKDA8MCgsOCwkJDRENDg8QEBEQCgwSExIQEw8QEBD/2wBDAQMDAwQDBAgEBAgQCwkLEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBD/wAARCAACAAIDAREAAhEBAxEB/8QAFAABAAAAAAAAAAAAAAAAAAAABv/EABQQAQAAAAAAAAAAAAAAAAAAAAD/xAAVAQEBAAAAAAAAAAAAAAAAAAAHCP/EABQRAQAAAAAAAAAAAAAAAAAAAAD/2gAMAwEAAhEDEQA/AC6iBU//2Q==',
  'gif': 'R0lGODlhAgACAPAAAER3zAAAACH5BAAAAAAALAAAAAACAAIAAAIChFEAOw==',
  'webp': 'UklGRjYAAABXRUJQVlA4ICoAAACQAQCdASoCAAIAAgA0JaACdLoAA5gA/uQBf/M0feb7LepP/sWctgWIAAA=',
};
